version: 2
jobs:
  build:
    docker:
      - image: rust:buster

    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

      - run:
          name: Print cargo version
          command: cargo --version

      - run:
          name: Print arch info
          command: lscpu

      - run:
          name: Update archives
          command: apt-get update && apt-get upgrade -y

      - run:
          name: Install build dependencies
          command: apt-get install -y pkg-config build-essential cmake libssl-dev

      - run:
          name: Build release
          command: cargo build --release

      - store_artifacts:
          path: ./target/release/patreon-proxy
          destination: patreon-proxy

      - store_artifacts:
          path: ./target/release/public
          destination: public-sharder

      - store_artifacts:
          path: ./target/release/whitelabel
          destination: whitelabel-sharder

      - store_artifacts:
          path: ./target/release/vote_listener
          destination: vote_listener

      - store_artifacts:
          path: ./target/release/http-gateway
          destination: http-gateway

      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
            - target/release/incremental
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}